api/models/Pet.js
api/models/User.js

Creación de los modelos de las mascotas  y usuarios.

Pet and User models done

---

api/models/Product.js

Creación del modelo de los productos.

Product model created

---

api/models/User.js

Se agregaron las propiedades "favorites" y "cart" al modelo de los usuarios.

added favorites and cart to the User model

---

api/src/models/Pet.js
api/src/models/Product.js
api/src/models/User.js

Se agregó la propiedad "Hidden" a los modelos para poder ocultar usuarios/mascotas/productos.

Hidden property

---

api/app.js
api/src/index.js
api/src/routes/Auth/routeAuth.js
api/src/routes/pets/detail.js
api/src/routes/pets/getFilteredPets.js
api/src/routes/pets/postPet.js
api/src/routes/pets/updatePet.js

Se modificaron los requiere de diferentes archivos

Correciones ruteo

---

api/src/routes/pets/detail.js
api/src/routes/products/e-shop.js
api/src/routes/users/profile.js

También se hizo borrado lógico para el detalle de la mascota (solo para mayor seguridad).

Borrado lógico para usuario. 

---

client/lib/mongodb.ts
client/package.json
client/pages/api/auth/[...nextauth].js

creacion de carpeta lib, archivo auth y configuracion de variables de entorno en el front

se agregó la autenticacion de google a la base de datos mongo

---

client/pages/login.js

seteo de estado local al hacer el submit

seteo de estado lo cal luego del submit

---

client/components/Footer/footer.js
client/components/NavBar/NavBar.js
client/components/infoHome/nosotros.js
client/pages/home/index.jsx
client/pages/login/index.jsx

Se acomodaron las importaciones en componentes y redireccionamiento de links

importaciones acomodadas

---

api/src/routes/Auth/routeAuth.js
client/pages/login/index.jsx
client/pages/profile/index.jsx
client/pages/signup/index.jsx

separacion de ruta login y signup y se agrego imagen predeterminada en auth user post

rutas e imagen predeterminada

---

client/components/Card/index.js
client/package.json
client/pages/detail/[id]/index.jsx
client/pages/petsPosts/index.jsx
client/stores/actions.js
client/stores/mascotas.js

Detail route unfinished

---

client/components/FormAuth/Login.js
client/components/FormAuth/Register.js
client/controller/validationLogin.js
client/controller/validationSignUp.js

validacion de formulario login y signup

validacion de formularios

---

client/components/FormAuth/Login.js
client/components/FormAuth/Register.js
client/pages/adoptionForm/index.jsx
client/pages/home/index.jsx
client/pages/login/index.jsx
client/pages/login/styles.module.css

login y signup css

---

client/components/AdoptionForm/AdoptionForm1.js
client/components/AdoptionForm/AdoptionForm2.js
client/controller/validationPostPet.jsx
client/pages/adoptionForm/[id].jsx
client/pages/adoptionForm/style.module.css
client/stores/actions.js

listo el formulario y le agregue un alert para que llenen todos los input y para cuando es invalida la imagen

css form post pet y agregue alert

---

client/pages/petsPosts/styles.module.css

filtros separados del logo
container de cards ocupando toda la pantalla

cambio de posicion de filtro de mascotas y posicion de mascotas

---

client/components/NavBar/NavBar.js
client/pages/adoptionForm/[id].jsx
client/pages/detail/[id].jsx
client/pages/favorites/index.jsx
client/pages/petsPosts/styles.module.css

loading listo

---

client/components/cardsCart/CardProduct.js
client/components/cardsCart/style.module.css
client/controller/functionsCart/deleteProduct.js
client/controller/functionsCart/getProduct.js
client/pages/_app.jsx
client/pages/cart/index.jsx
client/pages/cart/styles.module.css
client/pages/eShop/detail/[id].js

Ahora ya se pueden agregar o descontar la cantidad de un producto desde el carrito

added styles and logic in route cart

---

api/src/models/Pet.js
api/src/routes/pets/postPet.js
client/components/AdoptionForm/AdoptionForm2.js
client/controller/validationPostPet.jsx
client/pages/adoptionForm/[id].jsx

ya el front envia la informacion, falta que el back configure las imagenes

permitir subir varias fotos de las mascotas

---

api/app.js
api/src/models/Pet.js
api/src/routes/pets/postPet.js
client/components/AdoptionForm/AdoptionForm2.js
client/pages/detail/[id].jsx

subida y renderizado de imagenes multiples de la mascota

imagenes multiples

---

client/components/GoogleMap/Maps.js
client/controller/validationPostPet.jsx

deje un pequeño comentario en el componente map para que si alguien lo quiere reutilizar pueda saber como hacerlo

fixed post pet and prepare the Map component so that it can be reused
